version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"   # UI: http://localhost:15672  (guest/guest)

  sensors-api:
    build: ./api-sensors-node
    ports: ["3000:3000"]
    depends_on: [redis]
    environment:
      - REDIS_HOST=redis
      - EVENTOS_URL=http://eventos-api:5000/evento

  eventos-api:
    build: ./api-eventos-python
    ports: ["5000:5000"]
    depends_on: [redis, rabbitmq]
    environment:
      - REDIS_HOST=redis
      - RABBIT_HOST=rabbitmq

  logistics-api:
    build: ./api-logistica-php
    ports: ["8000:8000"]
    depends_on: [rabbitmq]
    environment:
      - RABBIT_HOST=rabbitmq
